// react-app/src/App.jsx
import { useState, useRef } from "react";
import {
  generateRows,
  generateUpdateSequence,
  formatVolume,
  formatPrice,
  formatChange,
  formatPercent,
} from "./data.js";
import Row from "./components/Row.jsx";

// Updated constants for 10,000 rows
const ROW_COUNT = 10000;
const allRows = generateRows(ROW_COUNT);
const swapRows = generateRows(ROW_COUNT, ROW_COUNT - 1);

// Updating 500 rows per tick (5% of the data) for 100 ticks
const updateSequence = generateUpdateSequence(ROW_COUNT, 500, 100);

function App() {
  const [rows, setRows] = useState([]);
  const [lastResult, setLastResult] = useState("");
  const intervalRef = useRef(null);

  function measureEnd(name) {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        performance.mark(name + "-end");
        const measure = performance.measure(
          name,
          name + "-start",
          name + "-end",
        );
        setLastResult(`${name}: ${measure.duration.toFixed(2)}ms`);
        console.log(`${name}: ${measure.duration.toFixed(2)}ms`);
      });
    });
  }

  const handleMount = () => {
    if (rows.length > 0) {
      setRows([]);
    } else {
      performance.mark("mount-start");
      setRows(allRows);
      measureEnd("mount");
    }
  };

  const handleSort = () => {
    performance.mark("sort-start");
    setRows([...rows].sort((a, b) => b.price - a.price));
    measureEnd("sort");
  };

  const handleFrequentUpdates = () => {
    performance.mark("updates-start");
    let tick = 0;
    const id = setInterval(() => {
      setRows((prev) => {
        const next = [...prev];
        const updates = updateSequence[tick];
        for (const u of updates) {
          next[u.rowIndex] = {
            ...next[u.rowIndex],
            price: u.newPrice,
            change: u.newChange,
            changePercent: u.newChangePercent,
          };
        }
        return next;
      });
      tick++;
      if (tick >= 100) {
        clearInterval(id);
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            performance.mark("updates-end");
            const measure = performance.measure(
              "updates",
              "updates-start",
              "updates-end",
            );
            setLastResult(`updates: ${measure.duration.toFixed(2)}ms`);
            console.log(`updates: ${measure.duration.toFixed(2)}ms`);
          });
        });
      }
    }, 100);
    intervalRef.current = id;
  };

  const handleSwap = () => {
    performance.mark("swap-start");
    setRows(swapRows);
    measureEnd("swap");
  };

  const handlePartialUpdate = () => {
    performance.mark("partial-start");
    setRows(
      rows.map((row, i) =>
        i % 10 === 0 ? { ...row, highlighted: !row.highlighted } : row,
      ),
    );
    measureEnd("partial");
  };

  return (
    <div className="app">
      <h1 className="app-title">React Energy Benchmark</h1>
      <div className="control-panel">
        <button
          className="primary"
          id="btn-mount"
          onClick={handleMount}
        >
          {rows.length > 0 ? "Clear" : "Mount 10,000 Rows"}
        </button>
        <button id="btn-sort" onClick={handleSort} disabled={rows.length === 0}>
          Sort by Price
        </button>
        <button onClick={handleFrequentUpdates} disabled={rows.length === 0}>
          Frequent Updates (10s)
        </button>
        <button id="btn-swap" onClick={handleSwap} disabled={rows.length === 0}>
          Swap All Rows
        </button>
        <button onClick={handlePartialUpdate} disabled={rows.length === 0}>
          Partial Update
        </button>
      </div>
      {lastResult && <div className="results">Last: {lastResult}</div>}
      <div className="row-count">{rows.length} rows rendered</div>
      <div className="data-grid-container">
        <table className="data-grid">
          <thead>
            <tr>
              <th>ID</th>
              <th>Ticker</th>
              <th>Company</th>
              <th>Price</th>
              <th>Change</th>
              <th>Change %</th>
              <th>Volume</th>
              <th>Sector</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <Row key={row.id} row={row} />
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default App;

// vue-app/src/App.vue
<script setup>
import { ref, shallowRef } from "vue";
import { generateRows, generateUpdateSequence } from "./data.js";
import Row from "./components/Row.vue";

// Updated constants for 10,000 rows
const ROW_COUNT = 10000;
const allRows = generateRows(ROW_COUNT);
const swapRows = generateRows(ROW_COUNT, ROW_COUNT - 1);

// Updating 500 rows per tick (5% of the data) for 100 ticks
const updateSequence = generateUpdateSequence(ROW_COUNT, 500, 100);

const rows = shallowRef([]);
const lastResult = ref("");

function measureEnd(name) {
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      performance.mark(name + "-end");
      const m = performance.measure(name, name + "-start", name + "-end");
      lastResult.value = `${name}: ${m.duration.toFixed(2)}ms`;
      console.log(`${name}: ${m.duration.toFixed(2)}ms`);
    });
  });
}

function handleMount() {
  if (rows.value.length > 0) {
    rows.value = [];
    return;
  }
  performance.mark("mount-start");
  rows.value = allRows;
  measureEnd("mount");
}

function handleSort() {
  performance.mark("sort-start");
  rows.value = [...rows.value].sort((a, b) => b.price - a.price);
  measureEnd("sort");
}

function handleFrequentUpdates() {
  performance.mark("updates-start");
  let tick = 0;
  const id = setInterval(() => {
    const current = [...rows.value];
    const updates = updateSequence[tick];
    for (const u of updates) {
      current[u.rowIndex] = {
        ...current[u.rowIndex],
        price: u.newPrice,
        change: u.newChange,
        changePercent: u.newChangePercent,
      };
    }
    rows.value = current;
    tick++;
    if (tick >= 100) {
      clearInterval(id);
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          performance.mark("updates-end");
          const m = performance.measure(
            "updates",
            "updates-start",
            "updates-end",
          );
          lastResult.value = `updates: ${m.duration.toFixed(2)}ms`;
          console.log(`updates: ${m.duration.toFixed(2)}ms`);
        });
      });
    }
  }, 100);
}

function handleSwap() {
  performance.mark("swap-start");
  rows.value = swapRows;
  measureEnd("swap");
}

function handlePartialUpdate() {
  performance.mark("partial-start");
  rows.value = rows.value.map((row, i) =>
    i % 10 === 0 ? { ...row, highlighted: !row.highlighted } : row,
  );
  measureEnd("partial");
}
</script>

<template>
  <div class="app">
    <h1 class="app-title">Vue Energy Benchmark</h1>
    <div class="control-panel">
      <button class="primary" id="btn-mount" @click="handleMount">
        {{ rows.length > 0 ? "Clear" : "Mount 10,000 Rows" }}
      </button>
      <button @click="handleSort" :disabled="rows.length === 0" id="btn-sort">
        Sort by Price
      </button>
      <button @click="handleFrequentUpdates" :disabled="rows.length === 0">
        Frequent Updates (10s)
      </button>
      <button @click="handleSwap" :disabled="rows.length === 0" id="btn-swap">
        Swap All Rows
      </button>
      <button @click="handlePartialUpdate" :disabled="rows.length === 0">
        Partial Update
      </button>
    </div>
    <div v-if="lastResult" class="results">Last: {{ lastResult }}</div>
    <div class="row-count">{{ rows.length }} rows rendered</div>
    <div class="data-grid-container">
      <table class="data-grid">
        <thead>
          <tr>
            <th>ID</th>
            <th>Ticker</th>
            <th>Company</th>
            <th>Price</th>
            <th>Change</th>
            <th>Change %</th>
            <th>Volume</th>
            <th>Sector</th>
          </tr>
        </thead>
        <tbody>
          <Row v-for="row in rows" :key="row.id" :row="row" />
        </tbody>
      </table>
    </div>
  </div>
</template>
